---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - default_vars.yml
    - servicenow-credentials.yml

  tasks:

  - name: Retrieve ServiceNow Table
    uri:
      url: https://dev71868.service-now.com/api/now/table/{{ snow_table }}
      method: GET
      user: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      force_basic_auth: yes
      body_format: json
    register: uri_output

  - name: Print output of {{ snow_table }} contents in JSON format
    debug:
      var: uri_output.json

  - name: Print API call status
    debug:
      var: uri_output.status
