---
- name: RAISE AN INCIDENT
  hosts: rtr1
  connection: local
  gather_facts: no
  tasks:

    - name: set vendor fact by network platform
      block:
        - name: Set vendor fact to cisco
          set_fact: vendor="cisco"

        - name: "gather_facts: yes"
          ios_facts:
            gather_subset: all
      when: ansible_network_os == "ios"


    - name: Create a network host record for {{ inventory_hostname }}
      snow_record:
        state: present
        table: cmdb_ci_linux_server
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        instance: "{{ SN_INSTANCE }}"
        data:
          name: "{{ inventory_hostname }}"
          host_name: "{{ inventory_hostname }}"
          manufacturer: "{{ vendor }}"
          firmware_manufacturer: "{{ vendor }}"
          device_type: router
          model_number: "{{ ansible_net_iostype }}"
          assigned_to: "Sean Cavanaugh"
          os_version: "{{ ansible_net_version }}"
          serial_number: "{{ ansible_net_serialnum }}"
          ip_address: "{{ ansible_host }}"
          mac_address: '{{ ansible_facts.net_interfaces["GigabitEthernet1"].macaddress }}'
          ports: '{{ ansible_facts.net_interfaces["GigabitEthernet1"].mediatype }}'
          ram: '{{ ansible_net_memtotal_mb }}'
        number: 95ec64c5db353300bb392a9a4896197b
      register: new_host
      delegate_to: localhost
      run_once: true

# - debug: var=new_host.record
# - debug: var=ansible_facts
